# Generated by Django 4.2.2 on 2023-06-29 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_prefernce_newsletter_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_email_verified',
            new_name='is_phone_verified',
        ),
    ]
