# Generated by Django 4.2.2 on 2023-06-29 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_is_email_verified_user_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
    ]
