# Generated by Django 4.2.2 on 2023-06-29 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_date_of_birth_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_sid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
