version: '3.8'

services:
  backend:
    build:
      context: ./api
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./api/.env
    volumes:
      - static_volume:/api/static
      - media_volume:/api/media

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    image: my-frontend
    depends_on:
      - backend

  nginx:
    image: my-frontend
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media

      - ./nginx:/etc/nginx/conf.d
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot 
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certbot-etc:
  certbot-var:
  certbot-data:

