version: '3.8'

services:
  backend:
    build:
      context: ./api
    command: gunicorn api.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./api/.env
    volumes:
      - static_volume:/api/static
      - media_volume:/api/media

  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    image: my-frontend
    depends_on:
      - backend

  nginx:
    image: my-frontend
    volumes:
      - static_volume:/usr/share/nginx/html/static
      - media_volume:/usr/share/nginx/html/media

      - certbot-data:/var/www/certbot
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt 
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend
      - frontend

  # certbot:
  #   image : certbot/certbot
  #   volumes:
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - certbot-data:/var/www/certbot
  #   # command: certonly --webroot --webroot-path=/var/www/certbot --email simerly81@gmail.com --agree-tos --no-eff-email --keep-until-expiring -d brolympic.com -d www.brolympic.com 

volumes:
  postgres_data:
  static_volume:
  media_volume:
  certbot-etc:
  certbot-var:
  certbot-data:

