# Generated by Django 4.2.2 on 2023-06-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0002_rename_name_country_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='brolympics',
            name='name',
            field=models.CharField(default='test name', max_length=60),
            preserve_default=False,
        ),
    ]
