# Generated by Django 4.2.2 on 2023-07-05 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0003_brolympics_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brolympics',
            name='name',
        ),
    ]
