# Generated by Django 4.2.2 on 2023-07-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0004_remove_brolympics_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition_H2H',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_1_score', models.IntegerField()),
                ('team_2_score', models.IntegerField()),
                ('active', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameModel(
            old_name='IndividualCompetition',
            new_name='Competition_Ind',
        ),
        migrations.RenameField(
            model_name='overallbrolympicsranking',
            old_name='ranking',
            new_name='rank',
        ),
        migrations.RemoveField(
            model_name='brolympics',
            name='ended',
        ),
        migrations.RemoveField(
            model_name='brolympics',
            name='n_teams',
        ),
        migrations.RemoveField(
            model_name='brolympics',
            name='started',
        ),
        migrations.RemoveField(
            model_name='eventranking_h2h',
            name='ranking',
        ),
        migrations.RemoveField(
            model_name='overallbrolympicsranking',
            name='win_rate',
        ),
        migrations.AddField(
            model_name='brolympics',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brolympics',
            name='name',
            field=models.CharField(default='Test Name', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brolympics',
            name='registration_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='brolympics',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='round_robin_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventranking_h2h',
            name='rank',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventranking_h2h',
            name='score_against',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventranking_h2h',
            name='score_for',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventranking_h2h',
            name='sos_losses',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventranking_h2h',
            name='sos_ties',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventranking_h2h',
            name='sos_wins',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventranking_h2h',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='team_h2h_event_rankings', to='brolympics.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventranking_individual',
            name='player_1_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventranking_individual',
            name='player_2_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventranking_individual',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='team_ind_event_rankings', to='brolympics.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overallbrolympicsranking',
            name='losses',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overallbrolympicsranking',
            name='ties',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overallbrolympicsranking',
            name='wins',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='brolympics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='brolympics.brolympics'),
        ),
        migrations.AlterField(
            model_name='eventranking_h2h',
            name='earned_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventranking_h2h',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_h2h_event_rankings', to='brolympics.event'),
        ),
        migrations.AlterField(
            model_name='eventranking_individual',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ind_event_rankings', to='brolympics.event'),
        ),
        migrations.AlterField(
            model_name='team',
            name='brolympics',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='brolympics.brolympics'),
        ),
        migrations.DeleteModel(
            name='H2hCompetition',
        ),
        migrations.AddField(
            model_name='competition_h2h',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='h2h_comps', to='brolympics.event'),
        ),
        migrations.AddField(
            model_name='competition_h2h',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='h2h_comp_losses', to='brolympics.team'),
        ),
        migrations.AddField(
            model_name='competition_h2h',
            name='team_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='h2h_comp_team_1', to='brolympics.team'),
        ),
        migrations.AddField(
            model_name='competition_h2h',
            name='team_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='h2h_comp_team_2', to='brolympics.team'),
        ),
        migrations.AddField(
            model_name='competition_h2h',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='h2h_comp_wins', to='brolympics.team'),
        ),
    ]
