# Generated by Django 4.2.2 on 2023-07-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0005_competition_h2h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition_ind',
            name='individual_scores',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='competition_ind',
            name='team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventranking_individual',
            name='individual_scores',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='competition_h2h',
            name='team_1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition_h2h',
            name='team_2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition_ind',
            name='player_1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition_ind',
            name='player_2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='concluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='n_active_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventranking_h2h',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventranking_h2h',
            name='sos_losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventranking_h2h',
            name='sos_ties',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventranking_h2h',
            name='sos_wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventranking_h2h',
            name='ties',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventranking_h2h',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventranking_individual',
            name='earned_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='eventranking_individual',
            name='player_1_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventranking_individual',
            name='player_2_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventranking_individual',
            name='ranking',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='eventranking_individual',
            name='team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overallbrolympicsranking',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overallbrolympicsranking',
            name='ties',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overallbrolympicsranking',
            name='total_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='overallbrolympicsranking',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='losses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='ties',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='wins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
