# Generated by Django 4.2.2 on 2023-07-06 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0006_competition_ind_individual_scores_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_player', models.PositiveIntegerField(default=4)),
                ('is_active', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_losers_bracket', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BracketMatchup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed_top', models.PositiveIntegerField()),
                ('seed_bottom', models.PositiveIntegerField()),
                ('bracket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brolympics.bracket')),
            ],
        ),
        migrations.CreateModel(
            name='EventRanking_Ind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_individual_scores', models.BooleanField(default=True)),
                ('player_1_score', models.IntegerField(blank=True, null=True)),
                ('player_2_score', models.IntegerField(blank=True, null=True)),
                ('team_score', models.IntegerField(blank=True, null=True)),
                ('ranking', models.PositiveIntegerField(default=1)),
                ('earned_points', models.PositiveIntegerField(default=0)),
                ('is_final', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='brolympics',
            old_name='registration_open',
            new_name='is_registration_open',
        ),
        migrations.RenameField(
            model_name='competition_ind',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='competition_ind',
            old_name='complete',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='competition_ind',
            old_name='individual_scores',
            new_name='is_individual_scores',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='available',
            new_name='is_available',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='concluded',
            new_name='is_concluded',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='high_score_wins',
            new_name='is_high_score_wins',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='round_robin_complete',
            new_name='is_round_robin_complete',
        ),
        migrations.RenameField(
            model_name='eventranking_h2h',
            old_name='final',
            new_name='is_final',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='available',
            new_name='is_available',
        ),
        migrations.AddField(
            model_name='competition_h2h',
            name='is_bracket_comp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='competition_h2h',
            name='loser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='h2h_comp_losses', to='brolympics.team'),
        ),
        migrations.AlterField(
            model_name='competition_h2h',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='h2h_comp_wins', to='brolympics.team'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[('H', 'Head to Head'), ('I', 'Individual'), ('T', 'Team Score')], default='H', max_length=1),
        ),
        migrations.DeleteModel(
            name='EventRanking_Individual',
        ),
        migrations.AddField(
            model_name='eventranking_ind',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_ind_event_rankings', to='brolympics.event'),
        ),
        migrations.AddField(
            model_name='eventranking_ind',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_ind_event_rankings', to='brolympics.team'),
        ),
        migrations.AddField(
            model_name='bracketmatchup',
            name='competition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brolympics.competition_h2h'),
        ),
        migrations.AddField(
            model_name='bracketmatchup',
            name='previous_matchup_bottom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottom_bracket_matchup', to='brolympics.bracketmatchup'),
        ),
        migrations.AddField(
            model_name='bracketmatchup',
            name='previous_matchup_top',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_bracket_matchup', to='brolympics.bracketmatchup'),
        ),
    ]
