# Generated by Django 4.2.2 on 2023-07-07 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0007_bracket_bracketmatchup_eventranking_ind_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bracket',
            new_name='Bracket_4',
        ),
        migrations.RemoveField(
            model_name='competition_h2h',
            name='is_bracket_comp',
        ),
        migrations.AlterField(
            model_name='bracketmatchup',
            name='competition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brolympics.competition_h2h'),
        ),
        migrations.AlterField(
            model_name='competition_h2h',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='h2h_comp_team_1', to='brolympics.team'),
        ),
        migrations.AlterField(
            model_name='competition_h2h',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='h2h_comp_team_2', to='brolympics.team'),
        ),
    ]
