# Generated by Django 4.2.2 on 2023-07-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0008_rename_bracket_bracket_4_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bracketmatchup',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='bracketmatchup',
            name='previous_matchup_bottom',
        ),
        migrations.RemoveField(
            model_name='bracketmatchup',
            name='previous_matchup_top',
        ),
        migrations.RemoveField(
            model_name='bracketmatchup',
            name='seed_bottom',
        ),
        migrations.RemoveField(
            model_name='bracketmatchup',
            name='seed_top',
        ),
        migrations.AddField(
            model_name='bracketmatchup',
            name='team_1_seed',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bracketmatchup',
            name='team_2_seed',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
