# Generated by Django 4.2.2 on 2023-07-07 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0010_bracket_4_championship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bracket_4',
            name='event',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='brolympics.event'),
            preserve_default=False,
        ),
    ]
