# Generated by Django 4.2.2 on 2023-07-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0012_eventranking_h2h_win_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='n_bracket_teams',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
