# Generated by Django 4.2.2 on 2023-07-09 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0013_event_n_bracket_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='n_matches',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='brolympics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='brolympics.brolympics'),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
