# Generated by Django 4.2.2 on 2023-07-09 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0014_event_n_matches_alter_team_brolympics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracket_4',
            name='championship',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root', to='brolympics.bracketmatchup'),
        ),
        migrations.AlterField(
            model_name='bracket_4',
            name='loser_bracket_finals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser_root', to='brolympics.bracketmatchup'),
        ),
    ]
