# Generated by Django 4.2.2 on 2023-07-09 04:39

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0015_alter_bracket_4_championship_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bracketmatchup',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='bracketmatchup',
            old_name='complete',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='competition_h2h',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='competition_h2h',
            old_name='complete',
            new_name='is_complete',
        ),
        migrations.AddField(
            model_name='bracketmatchup',
            name='end_time',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bracketmatchup',
            name='start_time',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition_h2h',
            name='end_time',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition_h2h',
            name='start_time',
            field=models.DateTimeField(default=timezone.now()),
            preserve_default=False,
        ),
    ]
