# Generated by Django 4.2.2 on 2023-07-09 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0016_rename_active_bracketmatchup_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brolympics',
            old_name='completed',
            new_name='is_complete',
        ),
    ]
