# Generated by Django 4.2.2 on 2023-07-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0017_rename_completed_brolympics_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracketmatchup',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bracketmatchup',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition_h2h',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition_h2h',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
