# Generated by Django 4.2.2 on 2023-07-09 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0019_alter_event_max_score_alter_event_min_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventranking_h2h',
            old_name='earned_points',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='eventranking_ind',
            old_name='earned_points',
            new_name='points',
        ),
    ]
