# Generated by Django 4.2.2 on 2023-07-10 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0020_rename_earned_points_eventranking_h2h_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventranking_h2h',
            name='win_rate',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=6),
        ),
    ]
