# Generated by Django 4.2.2 on 2023-07-10 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0024_event_ind_event_h2h_alter_bracket_4_event_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bracket_4',
            old_name='is_completed',
            new_name='is_complete',
        ),
    ]
