# Generated by Django 4.2.2 on 2023-07-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0025_rename_is_completed_bracket_4_is_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_h2h',
            name='max_score',
            field=models.IntegerField(default=100),
        ),
    ]
