# Generated by Django 4.2.2 on 2023-07-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0026_alter_event_h2h_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
