# Generated by Django 4.2.2 on 2023-07-10 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0027_alter_team_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracketmatchup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='brolympics.event_h2h'),
        ),
        migrations.AlterField(
            model_name='bracketmatchup',
            name='loser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_comp_losses', to='brolympics.team'),
        ),
        migrations.AlterField(
            model_name='bracketmatchup',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_comp_team_1', to='brolympics.team'),
        ),
        migrations.AlterField(
            model_name='bracketmatchup',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_comp_team_2', to='brolympics.team'),
        ),
        migrations.AlterField(
            model_name='bracketmatchup',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_comp_wins', to='brolympics.team'),
        ),
        migrations.AlterField(
            model_name='competition_h2h',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='brolympics.event_h2h'),
        ),
        migrations.AlterField(
            model_name='competition_h2h',
            name='loser',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_comp_losses', to='brolympics.team'),
        ),
        migrations.AlterField(
            model_name='competition_h2h',
            name='team_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_comp_team_1', to='brolympics.team'),
        ),
        migrations.AlterField(
            model_name='competition_h2h',
            name='team_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_comp_team_2', to='brolympics.team'),
        ),
        migrations.AlterField(
            model_name='competition_h2h',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_comp_wins', to='brolympics.team'),
        ),
        migrations.AlterField(
            model_name='eventranking_h2h',
            name='points',
            field=models.FloatField(default=0),
        ),
    ]
