# Generated by Django 4.2.2 on 2023-07-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0028_alter_bracketmatchup_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_ind',
            name='player_1_score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bracketmatchup',
            name='team_1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bracketmatchup',
            name='team_2_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition_h2h',
            name='team_1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition_h2h',
            name='team_2_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition_ind',
            name='player_1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition_ind',
            name='player_2_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition_ind',
            name='team_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event_h2h',
            name='max_score',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='event_h2h',
            name='min_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='eventranking_h2h',
            name='score_against',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='eventranking_h2h',
            name='score_for',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='eventranking_ind',
            name='player_1_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventranking_ind',
            name='player_2_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventranking_ind',
            name='points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='eventranking_ind',
            name='team_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='overallbrolympicsranking',
            name='total_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
