# Generated by Django 4.2.2 on 2023-07-13 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0029_event_ind_player_1_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition_ind',
            name='is_individual_scores',
        ),
        migrations.RemoveField(
            model_name='event_ind',
            name='player_1_score',
        ),
        migrations.AddField(
            model_name='event_ind',
            name='brolympics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='brolympics.brolympics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_ind',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_ind',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event_ind',
            name='is_concluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event_ind',
            name='is_high_score_wins',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event_ind',
            name='is_individual_scores',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='event_ind',
            name='max_score',
            field=models.FloatField(default=100),
        ),
        migrations.AddField(
            model_name='event_ind',
            name='min_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='event_ind',
            name='n_active_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_ind',
            name='name',
            field=models.CharField(default='1', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event_ind',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition_ind',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_comp', to='brolympics.event_ind'),
        ),
    ]
