# Generated by Django 4.2.2 on 2023-07-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0030_remove_competition_ind_is_individual_scores_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventranking_ind',
            old_name='player_1_score',
            new_name='player_1_total_score',
        ),
        migrations.RenameField(
            model_name='eventranking_ind',
            old_name='player_2_score',
            new_name='player_2_total_score',
        ),
        migrations.RenameField(
            model_name='eventranking_ind',
            old_name='team_score',
            new_name='team_total_score',
        ),
        migrations.AddField(
            model_name='event_ind',
            name='n_competitions',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
