# Generated by Django 4.2.2 on 2023-07-13 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brolympics', '0032_eventranking_ind_player_1_avg_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventranking_ind',
            old_name='ranking',
            new_name='rank',
        ),
    ]
